# -*- coding: utf-8 -*-
"""resume_scanner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0wvd6bGWWpyQdxHzjEcrHdlAtSLsCf5
"""

#! pip install PyMuPDF

import fitz  # PyMuPDF
import spacy
import re
import json

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

def extract_text_from_pdf(file_path):
    doc = fitz.open(file_path)
    text = ''
    for page in doc:
        text += page.get_text()
    return text

def extract_name(doc):
    for ent in doc.ents:
        if ent.label_ == "PERSON":
            return ent.text
    return "Not Found"

def extract_email(text):
    match = re.search(r'[\w\.-]+@[\w\.-]+', text)
    return match.group(0) if match else "Not Found"

def extract_phone_number(text):
    phone_pattern = re.compile(r'(\+?\d[\d\s\-\(\)]{8,}\d)')
    match = phone_pattern.search(text)
    return match.group(0) if match else "Not Found"

SKILL_DB = ["Python", "Java", "C++", "Machine Learning", "SQL", "Data Analysis", "Excel", "AWS"]

def extract_skills(text, skill_db):
    return [skill for skill in skill_db if skill.lower() in text.lower()]

EDU_KEYWORDS = ['B.Tech', 'Bachelor', 'B.Sc', 'M.Tech', 'Master', 'PhD', 'MBA']

def extract_education(text):
    return [edu for edu in EDU_KEYWORDS if edu.lower() in text.lower()]

def extract_experience(text):
    experience_keywords = ["experience", "worked at", "intern", "project", "role"]
    exp_lines = [line.strip() for line in text.split('\n') if any(k in line.lower() for k in experience_keywords)]
    return exp_lines[:5]

def scan_resume(file_path):
    resume_text = extract_text_from_pdf(file_path)
    doc = nlp(resume_text)

    data = {
        "Name": extract_name(doc),
        "Email": extract_email(resume_text),
        "Phone": extract_phone_number(resume_text),
        "Skills": extract_skills(resume_text, SKILL_DB),
        "Education": extract_education(resume_text),
        "Experience": extract_experience(resume_text)
    }

    print(json.dumps(data, indent=2))


# Colab-compatible file upload
if __name__ == "__main__":
    path = "Sample-Resume.pdf"  # <- Change this to your resume file name
    scan_resume(path)